collegemeet/collegemeet/complete/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.home,
        name='home'
    ),
    url(regex=r'^createTopic/$', view=views.create_topic, name="create_topic"),
    url(regex=r'^createPost/$', view=views.create_post, name="create_post"),
    url(regex=r'^profile/$', view=views.get_user_profile, name="get_user_profile"),
    url(regex=r'^likePost/$', view=views.like_post, name="like_post"),
    url(regex=r'^sharePost/$', view=views.share_post, name="share_post"),
    url(regex=r'^viewTopic/(?P<topic_id>[\d]+)/$', view=views.view_topic, name="view_topic")

]

collegemeet/collegemeet/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    )
]

collegemeet/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('collegemeet.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^complete/', include('collegemeet.complete.urls', namespace='complete')),
    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

collegemeet/collegemeet/complete/models.py
from django.db import models
from collegemeet.users.models import User

class Topic(models.Model):

    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    description = models.CharField(max_length=1000)
    subscribers = models.ManyToManyField(User, related_name='subscribers')
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_post_count(self):
        return self.post_set.count()

    def total_subscribers(self):
        return self.subscribers.count()

class Post(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    description = models.CharField(max_length=5000)
    likes = models.ManyToManyField(User, related_name='likes')
    shares = models.ManyToManyField(User, related_name='shares')
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def get_comment_count(self):
        return self.postcomments_set.count()

    def total_likes(self):
        return self.likes.count()

    def total_shares(self):
        return self.shares.count()

    def __str__(self):
        return self.description

    class Meta:
        ordering = ['-updated_at']


class PostComments(models.Model):

    commenting_user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.CharField(max_length=1000)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

collegemeet/collegemeet/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    description = models.CharField(max_length=100)
    connections = models.ManyToManyField("self", related_name="connections")

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})


class ConnectionRequest(models.Model):
	sender = models.ForeignKey(User, related_name = "sender", on_delete=models.CASCADE)
	receiver = models.ForeignKey(User, related_name = "receiver", on_delete=models.CASCADE)

	created_at = models.DateTimeField(auto_now_add=True)

collegemeet/collegemeet/complete/forms.py
from django import forms
from .models import Topic, Post, PostComments

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['name', 'description']

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['description']

class PostCommentsForm(forms.ModelForm):
	class Meta:
		model = PostComments
		fields = ['comment']

collegemeet/collegemeet/complete/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from .forms import TopicForm, PostForm
from .models import Topic, Post, User
from collegemeet.users.models import User
from django.core.serializers.json import DjangoJSONEncoder

try:
	from django.utils import simplejson as json
except ImportError:
	import json

def home(request):
	return render(request, 'complete/home.html')

## Topic Endpoints Begin ##

def create_topic(request):
    if request.method == "POST":
        # calling the postform class and it is giving a dictionary and it validates
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = Topic(admin=request.user, name=form.cleaned_data['name'], description=form.cleaned_data['description'])
            topic.save()
            return redirect("complete:view_topic", topic_id=topic.id)
        else:
            return HttpResponse("There is an error")
    else:
        form = TopicForm()
        context = {
            "form": form,
        }
        return render(request, "complete/createTopic.html", context)

def view_topic(request, topic_id):
	return render(request, "complete/viewTopic.html")

def get_all_topics(request):
	admin = request.user
	context = {}
	topics = Topic.objects.all()
	context['topics'] = topics
	return render(request, "complete/showAllTopics.html", context)

def search_topic(request):
	query_string = ''
	found_entries = None
	if ('q' in request.GET) and request.GET['q'].strip(): #textboxname = q
		query_string = request.GET['q']
		entry_query = get_query(query_string, ['name', 'description', ])
		found_entries = Job.objects.filter(entry_query)
		context = {}
		context['query_string'] = query_string
		context['found_entries'] = found_entries
	return render(request, template_name = 'complete/searchResults.html', context = context)

def subscribe_topic(request):
	if request.method == "POST":
		topic_id = request.POST.get("topic_id") #need topic id

		user = request.user
		topic = Topic.objects.get(pk=topic_id)
		if is_user_subscribed_to_topic(user, topic):
			topic.subscribers.remove(user)
			subscribe_button_text = "unsubscribed"
		else:
			topic.subscribers.add(user)
			subscribe_button_text = "subscribed"

		topic.save()
		response = JsonResponse({'subscribe_button_text' : subscribe_button_text})
		return response

def is_user_subscribed_to_topic(user, topic):
	if topic.subscribers.filter(username=user.username).exists():
		return True
	else:
		return False

def view_members(request):
	return None

## Topic Endpoints Ends ##


## Post Endpoints Begin ##

'''
def create_post(request):
	if request.method == "POST":
		post_form = PostForm(request.POST)
		if post_form.is_valid():
			topic_id = request.POST.get("topic_id") #should get topic id from request object post data
			topic = Topic.objects.get(pk=topic_id)
			post = topic.post_set.create(description=form.cleaned_data['description'])
			topic.save()
			return redirect("complete:get_all_posts")
		else:
			return HttpResponse("Error Encountered!")
	else:
		form = PostForm()
		topics = Topic.objects.all()
		context = {
		"form": form,
		"topics": topics
		}
	return render(request, "complete/createPost.html", context)
'''
def create_post(request):
	if request.method == "POST":
		print(request.POST.get('postbox'))


def get_all_posts(request):
	user = request.user
	context = {}
	topic_id = request.POST.get("topic_id") #should get topic id from request object post data
	topic = Topic.objects.get(pk=topic_id)
	posts = topic.post_set.all()
	context['posts'] = posts
	return render(request, "complete/showAllPosts.html", context)

def is_user_post_liked(user, post):
	if post.likes.all().exists():
		if post.likes.filter(username=user.username).exists():
			return True
		else:
			return False
	else:
		return False

def like_post(request):
	if request.method == "POST":
		post_id = request.POST.get("post_id")

		user = request.user
		post = Post.objects.get(pk=post_id)

		if is_user_post_liked(user, post):
			post.likes.remove(user)
			like_button_text = "Like"
		else:
			post.likes.add(user)
			like_button_text = "UnLike"

		post.save()
		response = JsonResponse({'like_button_text': like_button_text})
		return response

def is_user_post_shared(user, post):
	if post.shares.filter(username=user.username).exists():
		return True
	else:
		return False

def share_post(request):
	if request.method == "POST":
		post_id = request.POST.get("post_id")

		user = request.user
		post = Post.objects.get(pk=post_id)

		if is_user_post_shared(user, post) == False:
			post.shares.add(user)
			post.save()
		
		share_button_text = "Shared"
		response = JsonResponse({'share_button_text' : share_button_text})
		return response

## Post Endpoints Ends ##

## User Endpoints Begins ##

'''
Input Required:
	{
	  'username': "sbhartia",
	  'name': "Shweta Bhartia",
	  'description': "Hi I am Shweta Bhartia"
	}

Output:

'''

def update_profile(request):
	username = request.POST.get("username")
	name = request.POST.get("name")
	description = request.get("description")

	user = User.objects.all().filter(username=username).update(name=name,description=description)
	try:
		user.save()
		JsonResponse({"status":"true","message":"updated succesfully"})
	except:
		JsonResponse({"status":"false","message":"Error!"}, status=500)

def get_user_profile(request):
    user = request.user
    response = JsonResponse({'username': user.username, 'name': user.name, 'description': user.description, 'connections': user.connections})
    return response

def send_friend_request(request):
	return None

## User Endpoints Ends ##

collegemeet/collegemeet/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User

from django.http import HttpResponse, JsonResponse

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

def get_user_profile(request):
    user = request.user
    response = JsonResponse(user)
    return response

collegemeet/collegemeet/templates/complete/createPost.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form class="form-horizontal" method="post" action="{% url 'complete:create_post' %}">
	{% csrf_token %}
	{{ form|crispy }}
	<select id="topic_selected">
	{% if topics %}
		{% for topic in topics %}
		<option value={{topic.id}}>{{topic.name}}</option>
		{% endfor %}
	{% else %}
		<option value="1">N/A</option>
	{% endif %}
	<select>
	<div class="control-group">
	  <div class="controls">
	    <button type="submit" class="btn">Submit</button>
	  </div>
	</div>
</form>
{% endblock %}

collegemeet/collegemeet/templates/complete/createTopic.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form class="form-horizontal" method="post" action="{% url 'complete:create_topic' %}">
	{% csrf_token %}
	{{ form|crispy }}
	<div class="control-group">
	  <div class="controls">
	    <button type="submit" class="btn">Submit</button>
	  </div>
	</div>
</form>
{% endblock %}

collegemeet/collegemeet/templates/complete/createUser.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form class="form-horizontal" method="post" action="{% url 'complete:create_user' %}">
	{% csrf_token %}
	{{ form|crispy }}
	<div class="control-group">
	  <div class="controls">
	    <button type="submit" class="btn">Submit</button>
	  </div>
	</div>
</form>
{% endblock %}

collegemeet/collegemeet/templates/complete/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	<h1>Welcome to the Collegemeet</h1>
{% endblock %}

collegemeet/collegemeet/templates/complete/showAllTopics.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="container">
		<h1>Show Topics</h1>
		{% if topics %}
			<ul>
				{% for topic in topics %}
					<li>
						<a href="{% url 'complete:get_topic' topic.id %}">{{topic.name}}</a>
					</li>
				{% endfor %}
			</ul>
		{% else %}
			<p>No topics found</p>
		{% endif %}
	</div>
{% endblock content %}

collegemeet/collegemeet/templates/complete/viewTopic.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block css %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
{{block.super}}
{% endblock %}

{% block content %}
	<!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title of the Topic -->
                <h1>Topic Name</h1>

                <!-- Author -->
                <p class="lead">
                    by <a href="#">Admin name</a>
                </p>

                <hr>

                <!-- Preview Image -->
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">

                <hr>

                <!-- Post Content -->
                <p class="lead">Topic Description</p>

                <hr>

                <!-- Blog Comments -->
                <div class="well">
	                <h4>Write a Post</h4>
	                <form action="{% url 'complete:createPost' %}" method="get">
	                    <div class="form-group">
	                        <textarea class="form-control" rows="3" name="postbox"></textarea>
	                    </div>
						<input type="submit" class="btn btn-primary" href="{% url 'complete:createPost' %}" value="Post">
	                </form>
                </div>

                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading">Posted By
                            <small>Posted Time</small>
                        </h4>
                        Random Description
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>
            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Topic Search Well -->
                <div class="well">
                    <h4>Topic Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Top 10 subscribers</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>

    </div>
{% endblock %}